global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'mysql'
    static_configs:
      - targets: [ 'host.docker.internal:9104' ]

  - job_name: 'redis'
    static_configs:
      - targets: [ 'host.docker.internal:9121' ]

  - job_name: 'kafka'
    static_configs:
      - targets: [ 'host.docker.internal:9308' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'host.docker.internal:9100' ]

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'host.docker.internal:9093' ]